/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class AddBinaryTest {

    @ParameterizedTest
    @MethodSource("provider")
    void test(String aBinary, String bBinary, String expected) {
        // setup
        AddBinary sol = new AddBinary();
        // execute
        String actual = sol.addBinary(aBinary, bBinary);
        // verify
        assertEquals(expected, actual);
    }

    static Stream<Arguments> provider() {
        return Stream.of( //
                Arguments.of("11", "1", "100"), //
                Arguments.of("1010", "1011", "10101"), //
                Arguments.of("10", "1", "11"), //
                Arguments.of("11111", "1111", "101110"), //
                Arguments.of("11111", "11111", "111110"), //
                Arguments.of("1", "1", "10") //
        );
    }
}
