/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class BalancedBinaryTreeTest {
  @ParameterizedTest
  @MethodSource("provider")
  void test(TreeNode root, boolean expected) {
    // setup
    BalancedBinaryTree sol = new BalancedBinaryTree();
    // execute
    boolean actual = sol.isBalanced(root);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of(
        Arguments.of(
            new TreeNode(3, new TreeNode(9), new TreeNode(20, new TreeNode(15), new TreeNode(7))), //
            true), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2, new TreeNode(3, new TreeNode(4), new TreeNode(4)), new TreeNode(3)),
                new TreeNode(2)), //
            false), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2, new TreeNode(3, new TreeNode(4), null), null),
                new TreeNode(2, null, new TreeNode(3, null, new TreeNode(4)))),
            false), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), null),
            true), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), new TreeNode(2)),
            true), //
        Arguments.of(
            new TreeNode(1, null, null),
            true), //
        Arguments.of(
            null,
            true) //
    );
  }
}
