/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class BestTimeToBuyAndSellStockTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] input, int expected) {
    // setup
    BestTimeToBuyAndSellStock sol = new BestTimeToBuyAndSellStock();
    // execute
    int actual = sol.maxProfit(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 1 }, 0), //
        Arguments.of(new int[] { 7, 1, 5, 3, 6, 4 }, 5), //
        Arguments.of(new int[] { 7, 6, 4, 3, 1 }, 0), //
        Arguments.of(new int[] { 2, 1, 4 }, 3), //
        Arguments.of(new int[] { 2, 9, 1, 5 }, 7));
  }
}
