/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.google.common.collect.Lists;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collections;
import java.util.List;
import java.util.stream.Stream;

class BinaryTreeInorderTraversalTest {

    @ParameterizedTest
    @MethodSource("provider")
    void test(TreeNode root, List<Integer> expected) {
        // setup
        BinaryTreeInorderTraversal sol = new BinaryTreeInorderTraversal();
        // execute
        List<Integer> actual = sol.inorderTraversal(root);
        // verify
        assertEquals(expected, actual);
    }

    static Stream<Arguments> provider() {
        return Stream.of(
                Arguments.of(new TreeNode(1, null, new TreeNode(2, new TreeNode(3), null)),
                        Lists.newArrayList(1, 3, 2)), //
                Arguments.of(null, Collections.emptyList()), //
                Arguments.of(new TreeNode(1, null, null), Lists.newArrayList(1)), //
                Arguments.of(
                        new TreeNode(1, new TreeNode(2, new TreeNode(3), new TreeNode(4)),
                                new TreeNode(5, new TreeNode(6), new TreeNode(7))),
                        Lists.newArrayList(3, 2, 4, 1, 6, 5, 7)), //
                Arguments.of(new TreeNode(1, new TreeNode(2, null, new TreeNode(3)), null),
                        Lists.newArrayList(2, 3, 1)) //
        );
    }
}
