/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ClimbingStairsTest {

    @ParameterizedTest
    @MethodSource("provider")
    void test(int n, int expected) {
        // setup
        ClimbingStairs sol = new ClimbingStairs();
        // execute
        int actual = sol.climbStairs(n);
        // verify
        assertEquals(expected, actual);
    }

    static Stream<Arguments> provider() {
        return Stream.of( //
                Arguments.of(1, 1), //
                Arguments.of(2, 2), //
                Arguments.of(3, 3), //
                Arguments.of(4, 5), //
                Arguments.of(5, 8), //
                Arguments.of(45, 1836311903) //
        );
    }
}
