/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ContainsDuplicate2Test {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] input, int val, boolean expected) {
    // setup
    ContainsDuplicate2 sol = new ContainsDuplicate2();
    // execute
    boolean actual = sol.containsNearbyDuplicate(input, val);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 1, 2, 3, 1 }, 3, true), //
        Arguments.of(new int[] { 1, 0, 1, 1 }, 1, true), //
        Arguments.of(new int[] { 1, 2, 3, 1, 2, 3 }, 2, false), //
        Arguments.of(new int[] { 1 }, 1, false), //
        Arguments.of(new int[] { 1, 1 }, 1, true) //
    );
  }
}
