/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ContainsDuplicateTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] input, boolean expected) {
    // setup
    ContainsDuplicate sol = new ContainsDuplicate();
    // execute
    boolean actual = sol.containsDuplicate(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 1, 2, 3, 1 }, true), //
        Arguments.of(new int[] { 1, 2, 3, 4 }, false), //
        Arguments.of(new int[] { 1, 1, 1, 3, 3, 4, 3, 2, 4, 2 }, true), //
        Arguments.of(new int[] { 1 }, false), //
        Arguments.of(new int[] { 1, 1 }, true) //
    );
  }
}
