/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ExcelSheetColumnTitleTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int input, String expected) {
    // setup
    ExcelSheetColumnTitle sol = new ExcelSheetColumnTitle();
    // execute
    String actual = sol.convertToTitle(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(1, "A"), //
        Arguments.of(28, "AB"), //
        Arguments.of(52, "AZ"), //
        Arguments.of(701, "ZY"), //
        Arguments.of(703, "AAA") //
    );
  }
}
