/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ExcelSheetColumnNumberTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(String input, int expected) {
    // setup
    ExcelSheetColumnNumber sol = new ExcelSheetColumnNumber();
    // execute
    int actual = sol.titleToNumber(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of("A", 1), //
        Arguments.of("AB", 28), //
        Arguments.of("AZ", 52), //
        Arguments.of("ZY", 701), //
        Arguments.of("AAA", 703) //
    );
  }
}
