/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class HappyNumberTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int n, boolean expected) {
    // setup
    HappyNumber sol = new HappyNumber();
    // execute
    boolean actual = sol.isHappy(n);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(19, true), //
        Arguments.of(2, false), //
        Arguments.of(1, true), //
        Arguments.of(25, false) //
    );
  }
}
