/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ImplementQueueUsingStacksTest {

  @Test
  void example1() {
    // setup
    MyQueue myQueue = new MyQueue();
    myQueue.push(1);
    myQueue.push(2);

    // execute
    int peek = myQueue.peek(); // return 1
    int pop = myQueue.pop(); // return 1
    boolean isEmpty = myQueue.empty(); // return False
    // verify
    assertEquals(peek, 1);
    assertEquals(pop, 1);
    assertFalse(isEmpty);
  }

  @Test
  void example2() {
    // setup
    MyQueue myQueue = new MyQueue();

    // execute
    myQueue.push(1);
    myQueue.push(2);
    myQueue.push(3);
    myQueue.push(4);
    assertEquals(1, myQueue.pop());
    myQueue.push(5);
    assertEquals(2, myQueue.pop());
    assertEquals(3, myQueue.pop());
    assertEquals(4, myQueue.pop());
    assertEquals(5, myQueue.pop());

    // execute
    assertTrue(myQueue.empty());
  }
}
