/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ImplementStackUsingQueuesTest {

  @Test
  void example1() {
    // setup
    MyStack myStack = new MyStack();
    myStack.push(1);
    myStack.push(2);

    // execute
    int top = myStack.top(); // return 2
    int pop = myStack.pop(); // return 2
    boolean isEmpty = myStack.empty(); // return False
    // verify
    assertEquals(top, 2);
    assertEquals(pop, 2);
    assertFalse(isEmpty);
  }
}
