/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class InvertBinaryTreeTest {
  @ParameterizedTest
  @MethodSource("provider")
  void test(TreeNode root, TreeNode expected) {
    // setup
    InvertBinaryTree sol = new InvertBinaryTree();
    // execute
    TreeNode actual = sol.invertTree(root);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of(
        Arguments.of(
            new TreeNode(4, new TreeNode(2, new TreeNode(1), new TreeNode(3)),
                new TreeNode(7, new TreeNode(6), new TreeNode(9))),
            new TreeNode(4, new TreeNode(7, new TreeNode(9), new TreeNode(6)),
                new TreeNode(2, new TreeNode(3), new TreeNode(1)))), //
        Arguments.of(
            new TreeNode(2, new TreeNode(1), new TreeNode(3)),
            new TreeNode(2, new TreeNode(3), new TreeNode(1))), //
        Arguments.of(
            null,
            null), //
        Arguments.of(
            new TreeNode(2),
            new TreeNode(2)), //
        Arguments.of(
            new TreeNode(2, new TreeNode(1), null),
            new TreeNode(2, null, new TreeNode(1))) //
    );
  }
}
