/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LengthOfLastWordTest {
    @Test
    void example1() {
        // setup
        LengthOfLastWord sol = new LengthOfLastWord();
        String input = "Hello World";
        // execute
        int actual = sol.lengthOfLastWord(input);
        // verify
        assertEquals(5, actual);
    }

    @Test
    void example2() {
        // setup
        LengthOfLastWord sol = new LengthOfLastWord();
        String input = "   fly me   to   the moon  ";
        // execute
        int actual = sol.lengthOfLastWord(input);
        // verify
        assertEquals(4, actual);
    }

    @Test
    void example3() {
        // setup
        LengthOfLastWord sol = new LengthOfLastWord();
        String input = "luffy is still joyboy";
        // execute
        int actual = sol.lengthOfLastWord(input);
        // verify
        assertEquals(6, actual);
    }

    @Test
    void example4() {
        // setup
        LengthOfLastWord sol = new LengthOfLastWord();
        String input = "l";
        // execute
        int actual = sol.lengthOfLastWord(input);
        // verify
        assertEquals(1, actual);
    }

    @Test
    void example5() {
        // setup
        LengthOfLastWord sol = new LengthOfLastWord();
        String input = "word";
        // execute
        int actual = sol.lengthOfLastWord(input);
        // verify
        assertEquals(4, actual);
    }
}
