/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class MajorityElementTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] input, int expected) {
    // setup
    MajorityElement sol = new MajorityElement();
    // execute
    int actual = sol.majorityElement(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 3, 2, 3 }, 3), //
        Arguments.of(new int[] { 2, 2, 1, 1, 1, 2, 2 }, 2), //
        Arguments.of(new int[] { 3, 3 }, 3), //
        Arguments.of(new int[] { -1 }, -1) //
    );
  }
}
