/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class MaximumDepthOfBinaryTreeTest {
  @ParameterizedTest
  @MethodSource("provider")
  void test(TreeNode p, int expected) {
    // setup
    MaximumDepthOfBinaryTree sol = new MaximumDepthOfBinaryTree();
    // execute
    int actual = sol.maxDepth(p);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of(
        Arguments.of(
            new TreeNode(3, new TreeNode(9), new TreeNode(20, new TreeNode(15), new TreeNode(7))),
            3), //
        Arguments.of(
            new TreeNode(1, null, new TreeNode(2)),
            2), //
        Arguments.of(
            new TreeNode(1),
            1), //
        Arguments.of(
            null,
            0), //
        Arguments.of(
            new TreeNode(3, new TreeNode(9),
                new TreeNode(20, new TreeNode(15, new TreeNode(2), null), new TreeNode(7))),
            4) //
    );
  }
}
