/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MaxSubArrayTest {
    @Test
    void example1() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { -2, 1, -3, 4, -1, 2, 1, -5, 4 };
        // execute
        int actual = sol.maxSubArray(input);
        // verify
        assertEquals(6, actual);
    }

    @Test
    void example2() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { 1 };
        // execute
        int actual = sol.maxSubArray(input);
        // verify
        assertEquals(1, actual);
    }

    @Test
    void example3() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { 5, 4, -1, 7, 8 };
        // execute
        int actual = sol.maxSubArray(input);
        // verify
        assertEquals(23, actual);
    }

    @Test
    void example4() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { -2, 1, -3, 4, -1, 2, 1, -5, 4, 2 };
        // execute
        int actual = sol.maxSubArray(input);
        // verify
        assertEquals(7, actual);
    }

    @Test
    void example5() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { -1 };
        // execute
        int actual = sol.maxSubArray(input);
        // verify
        assertEquals(-1, actual);
    }

    @Test
    void findMaxFromFirstTest1() {
        // setup
        MaxSubArray sol = new MaxSubArray();
        int[] input = { -2, 1, -3, 4, -1, 2, 1, -5 };
        // execute
        int actual = sol.findMax(input, 0);
        // verify
        assertEquals(2, actual);
    }
}
