/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class PalindromeLinkedListTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(ListNode head, boolean expected) {
    // setup
    PalindromeLinkedList sol = new PalindromeLinkedList();
    // execute
    boolean actual = sol.isPalindrome(head);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of( //
            new ListNode(2, new ListNode(1, new ListNode(1, new ListNode(2)))), //
            true), //
        Arguments.of( //
            new ListNode(1, new ListNode(2, new ListNode(2, new ListNode(1)))), //
            true), //
        Arguments.of( //
            new ListNode(2, new ListNode(1, new ListNode(2))), //
            true), //
        Arguments.of( //
            new ListNode(2, new ListNode(2)), //
            true), //
        Arguments.of( //
            new ListNode(2, new ListNode(1)), //
            false), //
        Arguments.of( //
            new ListNode(2), //
            true) //
    );
  }
}
