/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.google.common.collect.Lists;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

class PascalsTriangleTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int input, List<List<Integer>> expected) {
    // setup
    PascalsTriangle sol = new PascalsTriangle();
    // execute
    List<List<Integer>> actual = sol.generate(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(1, new ArrayList<>(Arrays.asList( //
            new ArrayList<>(Arrays.asList(1)) //
        ))), //
        Arguments.of(2, Lists.newArrayList( //
            Lists.newArrayList(1), //
            Lists.newArrayList(1, 1) //
        )), //
        Arguments.of(3, Lists.newArrayList( //
            Lists.newArrayList(1), //
            Lists.newArrayList(1, 1), //
            Lists.newArrayList(1, 2, 1) //
        )), //
        Arguments.of(4, Lists.newArrayList( //
            Lists.newArrayList(1), //
            Lists.newArrayList(1, 1), //
            Lists.newArrayList(1, 2, 1), //
            Lists.newArrayList(1, 3, 3, 1) //
        )), //
        Arguments.of(5, Lists.newArrayList( //
            Lists.newArrayList(1), //
            Lists.newArrayList(1, 1), //
            Lists.newArrayList(1, 2, 1), //
            Lists.newArrayList(1, 3, 3, 1), //
            Lists.newArrayList(1, 4, 6, 4, 1) //
        )) //
    );
  }
}
