/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.google.common.collect.Lists;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

class PascalsTriangle2Test {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int input, List<Integer> expected) {
    // setup
    PascalsTriangle2 sol = new PascalsTriangle2();
    // execute
    List<Integer> actual = sol.getRow(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(0,
            Lists.newArrayList(Arrays.asList(1)) //
        ), //
        Arguments.of(1,
            Lists.newArrayList(1, 1) //
        ), //
        Arguments.of(2,
            Lists.newArrayList(1, 2, 1) //
        ), //
        Arguments.of(3,
            Lists.newArrayList(1, 3, 3, 1) //
        ), //
        Arguments.of(4,
            Lists.newArrayList(1, 4, 6, 4, 1) //
        ) //
    );
  }
}
