/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class PathSumTest {
  @ParameterizedTest
  @MethodSource("provider")
  void test(TreeNode root, int targetSum, boolean expected) {
    // setup
    PathSum sol = new PathSum();
    // execute
    boolean actual = sol.hasPathSum(root, targetSum);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of(
        Arguments.of(
            new TreeNode(5, new TreeNode(4, new TreeNode(11, new TreeNode(7), new TreeNode(2)), null),
                new TreeNode(8, new TreeNode(13), new TreeNode(4, null, new TreeNode(1)))),
            22,
            true), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), new TreeNode(3)),
            5,
            false), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), null),
            1,
            false), //
        Arguments.of(
            new TreeNode(-2, new TreeNode(-3), null),
            -5,
            true), //
        Arguments.of(
            null,
            0,
            false), //
        Arguments.of(
            new TreeNode(1),
            2,
            false) //
    );
  }
}
