/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PlusOneTest {
    @Test
    void example1() {
        // setup
        PlusOne sol = new PlusOne();
        int[] input = { 1, 2, 3 };
        int[] expected = { 1, 2, 4 };
        // execute
        int[] actual = sol.plusOne(input);
        // verify
        assertArrayEquals(expected, actual);
    }

    @Test
    void example2() {
        // setup
        PlusOne sol = new PlusOne();
        int[] input = { 4, 3, 2, 1 };
        int[] expected = { 4, 3, 2, 2 };
        // execute
        int[] actual = sol.plusOne(input);
        // verify
        assertArrayEquals(expected, actual);
    }

    @Test
    void example3() {
        // setup
        PlusOne sol = new PlusOne();
        int[] input = { 9 };
        int[] expected = { 1, 0 };
        // execute
        int[] actual = sol.plusOne(input);
        // verify
        assertArrayEquals(expected, actual);
    }

    @Test
    void example4() {
        // setup
        PlusOne sol = new PlusOne();
        int[] input = { 9, 9, 9 };
        int[] expected = { 1, 0, 0, 0 };
        // execute
        int[] actual = sol.plusOne(input);
        // verify
        assertArrayEquals(expected, actual);
    }
}
