/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class PowerOfTwoTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int n, boolean expected) {
    // setup
    PowerOfTwo sol = new PowerOfTwo();
    // execute
    boolean actual = sol.isPowerOfTwo(n);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(1, true), //
        Arguments.of(16, true), //
        Arguments.of(3, false), //
        Arguments.of(0, false), //
        Arguments.of(-8, false) //
    );
  }
}
