/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class RemoveLinkedListElementsTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(ListNode head, int val, ListNode expected) {
    // setup
    RemoveLinkedListElements sol = new RemoveLinkedListElements();
    // execute
    ListNode actual = sol.removeElements(head, val);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of( //
            new ListNode(1,
                new ListNode(2, new ListNode(6, new ListNode(3, new ListNode(4, new ListNode(5, new ListNode(6))))))), //
            6,
            new ListNode(1, new ListNode(2, new ListNode(3, new ListNode(4, new ListNode(5)))))), //
        Arguments.of( //
            null, //
            1,
            null), //
        Arguments.of( //
            new ListNode(7,
                new ListNode(7, new ListNode(7, new ListNode(7)))), //
            7,
            null), //
        Arguments.of( //
            new ListNode(1,
                new ListNode(2)), //
            1,
            new ListNode(2)), //
        Arguments.of( //
            new ListNode(1), //
            2,
            new ListNode(1)) //
    );
  }
}
