/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class RemoveDuplicatesFromSortedListTest {

    @ParameterizedTest
    @MethodSource("provider")
    void test(ListNode x, ListNode expected) {
        // setup
        RemoveDuplicatesFromSortedList sol = new RemoveDuplicatesFromSortedList();
        // execute
        ListNode actual = sol.deleteDuplicates(x);
        // verify
        assertEquals(expected, actual);
    }

    static Stream<Arguments> provider() {
        return Stream.of( //
                Arguments.of( //
                        new ListNode(1, new ListNode(1, new ListNode(2))), //
                        new ListNode(1, new ListNode(2))), //
                Arguments.of( //
                        new ListNode(1, new ListNode(1, new ListNode(2, new ListNode(3, new ListNode(3))))), //
                        new ListNode(1, new ListNode(2, new ListNode(3)))), //
                Arguments.of( //
                        new ListNode(-2,
                                new ListNode(-2, new ListNode(-1, new ListNode(0, new ListNode(4, new ListNode(4)))))), //
                        new ListNode(-2, new ListNode(-1, new ListNode(0, new ListNode(4))))), //
                Arguments.of( //
                        new ListNode(0, new ListNode(0, new ListNode(0))), //
                        new ListNode(0)), //
                Arguments.of(new ListNode(1), new ListNode(1)), //
                Arguments.of(null, null) //
        );
    }
}
