/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class RemoveDuplicatesFromSortedArrayTest {
    @Test
    void example1() {
        // setup
        RemoveDuplicatesFromSortedArray sol = new RemoveDuplicatesFromSortedArray();
        int[] input = { 1, 1, 2 };
        int[] expected = { 1, 2, };
        // execute
        int actual = sol.removeDuplicates(input);
        // verify
        assertEquals(2, actual);
        assertArrayCustom(expected, input, actual);
    }

    @Test
    void example2() {
        // setup
        RemoveDuplicatesFromSortedArray sol = new RemoveDuplicatesFromSortedArray();
        int[] input = { 0, 0, 1, 1, 1, 2, 2, 3, 3, 4 };
        int[] expected = { 0, 1, 2, 3, 4 };
        // execute
        int actual = sol.removeDuplicates(input);
        // verify
        assertEquals(5, actual);
        assertArrayCustom(expected, input, actual);
    }

    @Test
    void example3() {
        // setup
        RemoveDuplicatesFromSortedArray sol = new RemoveDuplicatesFromSortedArray();
        int[] input = { 0 };
        int[] expected = { 0 };
        // execute
        int actual = sol.removeDuplicates(input);
        // verify
        assertEquals(1, actual);
        assertArrayCustom(expected, input, actual);
    }

    @Test
    void example4() {
        // setup
        RemoveDuplicatesFromSortedArray sol = new RemoveDuplicatesFromSortedArray();
        int[] input = { 0, 0, 0, 0 };
        int[] expected = { 0 };
        // execute
        int actual = sol.removeDuplicates(input);
        // verify
        assertEquals(1, actual);
        assertArrayCustom(expected, input, actual);
    }

    private void assertArrayCustom(int[] expected, int[] actual, int limit) {
        for (int i = 0; i < limit; i++) {
            assertEquals(actual[i], expected[i]);
        }
    }
}
