/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ReverseBitsTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int input, int expected) {
    // setup
    ReverseBits sol = new ReverseBits();
    // execute
    int actual = sol.reverseBits(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(1, -2147483648), //
        Arguments.of(43261596, 964176192), //
        Arguments.of(-3, -1073741825) //
    );
  }
}
