/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class SameTreeTest {
  @ParameterizedTest
  @MethodSource("provider")
  void test(TreeNode p, TreeNode q, boolean expected) {
    // setup
    SameTree sol = new SameTree();
    // execute
    boolean actual = sol.isSameTree(p, q);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of(
        Arguments.of(
            new TreeNode(1, new TreeNode(2), new TreeNode(3)),
            new TreeNode(1, new TreeNode(2), new TreeNode(3)),
            true), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), null),
            new TreeNode(1, null, new TreeNode(2)),
            false), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), new TreeNode(1)),
            new TreeNode(1, new TreeNode(1), new TreeNode(2)),
            false), //
        Arguments.of(
            new TreeNode(1, new TreeNode(2), new TreeNode(3)),
            new TreeNode(1, new TreeNode(2), new TreeNode(3)),
            true), //
        Arguments.of(
            new TreeNode(0),
            new TreeNode(0),
            true), //
        Arguments.of(
            null, null, true), //
        Arguments.of(
            null,
            new TreeNode(0),
            false) //
    );
  }
}
