/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class SearchInsertPositionTest {
    @Test
    void example1() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1, 3, 5, 6 };
        int target = 5;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(2, actual);
    }

    @Test
    void example2() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1, 3, 5, 6 };
        int target = 2;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(1, actual);
    }

    @Test
    void example3() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1, 3, 5, 6 };
        int target = 7;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(4, actual);
    }

    @Test
    void example4() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { -1 };
        int target = -2;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(0, actual);
    }

    @Test
    void example5() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1, 3, 4 };
        int target = 2;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(1, actual);
    }

    @Test
    void example6() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1 };
        int target = 1;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(0, actual);
    }

    @Test
    void example7() {
        // setup
        SearchInsertPosition sol = new SearchInsertPosition();
        int[] input = { 1, 3, 5, 6 };
        int target = 6;
        // execute
        int actual = sol.searchInsert(input, target);
        // verify
        assertEquals(3, actual);
    }
}
