/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class SingleNumberTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] input, int expected) {
    // setup
    SingleNumber sol = new SingleNumber();
    // execute
    int actual = sol.singleNumber(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 2, 2, 1 }, 1), //
        Arguments.of(new int[] { 4, 1, 2, 1, 2 }, 4), //
        Arguments.of(new int[] { 1 }, 1), //
        Arguments.of(new int[] { -1, 0, -1 }, 0), //
        Arguments.of(new int[] { 1, 2, 2 }, 1) //
    );
  }
}
