/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class SqrtTest {

    @ParameterizedTest
    @MethodSource("provider")
    void test(int x, int expected) {
        // setup
        Sqrt sol = new Sqrt();
        // execute
        int actual = sol.mySqrt(x);
        // verify
        assertEquals(expected, actual);
    }

    static Stream<Arguments> provider() {
        return Stream.of( //
                Arguments.of(4, 2), //
                Arguments.of(8, 2), //
                Arguments.of(1, 1), //
                Arguments.of(2, 1), //
                Arguments.of(3, 1), //
                Arguments.of(2147395599, 46339), //
                Arguments.of(122, 11) //
        );
    }
}
