/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

class SummaryRangesTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(int[] nums, List<String> expected) {
    // setup
    SummaryRanges sol = new SummaryRanges();
    // execute
    List<String> actual = sol.summaryRanges(nums);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of(new int[] { 0, 1, 2, 4, 5, 7 }, Arrays.asList("0->2", "4->5", "7")), //
        Arguments.of(new int[] { 0, 2, 3, 4, 6, 8, 9 }, Arrays.asList("0", "2->4", "6", "8->9")), //
        Arguments.of(new int[] { 0 }, Arrays.asList("0")), //
        Arguments.of(new int[] { 0, 2 }, Arrays.asList("0", "2")), //
        Arguments.of(new int[] {}, Arrays.asList()), //
        Arguments.of(new int[] { 0, 1 }, Arrays.asList("0->1")) //
    );
  }
}
