/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ValidPalindromeTest {

  @ParameterizedTest
  @MethodSource("provider")
  void test(String input, boolean expected) {
    // setup
    ValidPalindrome sol = new ValidPalindrome();
    // execute
    boolean actual = sol.isPalindrome(input);
    // verify
    assertEquals(expected, actual);
  }

  static Stream<Arguments> provider() {
    return Stream.of( //
        Arguments.of("A man, a plan, a canal: Panama", true), //
        Arguments.of("race a car", false), //
        Arguments.of(" ", true), //
        Arguments.of(".,", true), //
        Arguments.of("an n a", true) //
    );
  }
}
