/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class AddBinary {
    public String addBinary(String a, String b) {
        String result = "";
        boolean isCarried = false;
        int longerLength = Math.max(a.length(), b.length());

        for (int i = 0; i < longerLength + 1; i++) {
            char aChar = i >= a.length() ? '0' : a.charAt(a.length() - i - 1);
            char bChar = i >= b.length() ? '0' : b.charAt(b.length() - i - 1);

            if (aChar == '0' && bChar == '0') {
                if (isCarried) {
                    result = "1" + result;
                } else {
                    result = "0" + result;
                }
                isCarried = false;
            } else if (aChar == '1' && bChar == '1') {
                if (isCarried) {
                    result = "1" + result;
                } else {
                    result = "0" + result;
                }
                isCarried = true;
            } else {
                if (isCarried) {
                    result = "0" + result;
                    isCarried = true;
                } else {
                    result = "1" + result;
                    isCarried = false;
                }
            }

            if (i >= longerLength - 1 && !isCarried) {
                break;
            }
        }
        return result;
    }
}
