/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class BestTimeToBuyAndSellStock {
  public int maxProfit(int[] prices) {
    int result = Integer.MIN_VALUE;
    int curMin = Integer.MAX_VALUE;
    for (int val : prices) {
      curMin = Math.min(curMin, val);
      result = Math.max(result, val - curMin);
    }
    return result;
  }
}
