/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class BestTimeToBuyAndSellStock {
  public int maxProfit(int[] prices) {
    int result = 0;
    for (int i = 0; i < prices.length; i++) {
      for (int j = i + 1; j < prices.length; j++) {
        result = Math.max(result, prices[j] - prices[i]);
      }
    }
    return result;
  }
}
