/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.List;

public class BinaryTreePreorderTraversal {
  public List<Integer> preorderTraversal(TreeNode root) {
    List<Integer> result = new ArrayList<>();
    if (root == null) {
      return result;
    }
    preorderTraversal(root, result);
    return result;
  }

  private void preorderTraversal(TreeNode root, List<Integer> list) {
    list.add(root.val);
    if (root.left != null) {
      preorderTraversal(root.left, list);
    }
    if (root.right != null) {
      preorderTraversal(root.right, list);
    }
  }
}
