/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class ClimbingStairs {
    public int climbStairs(int n) {
        return step(n);
    }

    private int step(int n) {
        if (n == 1) {
            return 1;
        }
        if (n == 2) {
            return 2;
        }
        return step(n - 1) + step(n - 2);
    }
}
