/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ContainsDuplicate2 {
  public boolean containsNearbyDuplicate(int[] nums, int k) {
    Map<Integer, List<Integer>> map = new HashMap<>();
    for (int i = 0; i < nums.length; i++) {
      if (!map.containsKey(nums[i])) {
        map.put(nums[i], new ArrayList<>());
      }
      map.get(nums[i]).add(i);
    }

    for (Map.Entry<Integer, List<Integer>> entry : map.entrySet()) {
      if (entry.getValue().size() < 1) {
        continue;
      }
      int minGapIndex = Integer.MAX_VALUE;
      for (int i = 0; i < entry.getValue().size(); i++) {
        if (i == 0) {
          continue;
        }
        minGapIndex = Math.min(minGapIndex, entry.getValue().get(i) - entry.getValue().get(i - 1));
        if (minGapIndex <= k) {
          return true;
        }
      }
    }
    return false;
  }
}
