/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class ExcelSheetColumnNumber {
  public int titleToNumber(String columnTitle) {
    char[] chars = columnTitle.toCharArray();
    int digit = 1, result = 0;
    for (int i = chars.length - 1; i >= 0; --i) {
      result += digit * (chars[i] - 64);
      digit *= 26;
    }
    return result;
  }
}
