/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class ExcelSheetColumnTitle {
  public String convertToTitle(int columnNumber) {
    String result = "";
    while (true) {
      int remaining = columnNumber % 26;
      result = (remaining == 0 ? "Z" : (char) (remaining + 64)) + result;
      if (columnNumber <= 26) {
        break;
      }
      columnNumber = remaining == 0 ? (columnNumber / 26 - 1) : (columnNumber / 26);
    }
    return result;
  }
}
