/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.HashSet;
import java.util.Set;

public class HappyNumber {
  public boolean isHappy(int n) {
    Set<Integer> hist = new HashSet<>();
    while (true) {
      if (n == 1) {
        return true;
      }
      if (hist.contains(n)) {
        return false;
      }
      hist.add(n);
      n = calcHappyNumber(n);
    }
  }

  private int calcHappyNumber(int n) {
    int result = 0;
    int current = n;
    while (current > 0) {
      result += (int) Math.pow(current % 10, 2);
      current = current / 10;
    }
    return result;
  }
}
