/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

public class ImplementStrStr {
    public int strStr(String haystack, String needle) {
        if (needle.isEmpty()) {
            return 0;
        }
        if (haystack.length() < needle.length()) {
            return -1;
        }
        // first index to needle index
        Map<Integer, Integer> map = new HashMap<>();
        int ans = -1;
        for (int i = 0; i < haystack.length(); i++) {
            if (haystack.charAt(i) == needle.charAt(0)) {
                map.put(i, 0);
            }
            for (Iterator<Map.Entry<Integer, Integer>> it = map.entrySet().iterator(); it.hasNext();) {
                Map.Entry<Integer, Integer> entry = it.next();
                if (haystack.charAt(i) == needle.charAt(entry.getValue())) {
                    entry.setValue(entry.getValue() + 1);
                } else {
                    it.remove();
                }
                if (entry.getValue() == needle.length()) {
                    ans = entry.getKey();
                    break;
                }
            }
            if (ans > -1)
                break;
        }
        return ans;
    }
}
