/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class IntersectionOfTwoLinkedLists {
  public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
    while (headA != null) {
      ListNode found = find(headA, headB);
      if (found != null) {
        return found;
      }
      headA = headA.next;
    }
    return null;
  }

  private ListNode find(final ListNode root, ListNode head) {
    if (root == null || head == null) {
      return null;
    }
    if (root == head) {
      return root;
    }
    return find(root, head.next);
  }
}
