/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class IntersectionOfTwoLinkedLists {
  public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
    ListNode h1 = headA;
    ListNode h2 = headB;
    int h1len = 0;
    int h2len = 0;

    while (h1 != null) {
      h1len++;
      h1 = h1.next;
    }
    while (h2 != null) {
      h2len++;
      h2 = h2.next;
    }

    while (h1len != h2len) {
      if (h1len > h2len) {
        headA = headA.next;
        h1len--;
      } else {
        headB = headB.next;
        h2len--;
      }
    }

    while (headA != headB) {
      headA = headA.next;
      headB = headB.next;
    }
    return headA;
  }
}
