/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class IsomorphicStrings {
  public boolean isIsomorphic(String s, String t) {
    char[] sChar = s.toCharArray();
    char[] tChar = t.toCharArray();
    int[] sCharIndexArray = new int[256];
    int[] tCharIndexArray = new int[256];

    for (int i = 0; i < sChar.length; i++) {
      if (sCharIndexArray[sChar[i]] != 0 && sCharIndexArray[sChar[i]] != tChar[i]) {
        return false;
      }
      if (tCharIndexArray[tChar[i]] != 0 && tCharIndexArray[tChar[i]] != sChar[i]) {
        return false;
      }
      sCharIndexArray[sChar[i]] = tChar[i];
      tCharIndexArray[tChar[i]] = sChar[i];
    }
    return true;
  }
}
