/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class LengthOfLastWord {
    public int lengthOfLastWord(String s) {
        int start = -1;
        int end = -1;
        for (int i = s.length() - 1; i >= 0; i--) {
            if (end == -1 && s.charAt(i) != ' ') {
                end = i;
                continue;
            }
            if (end != -1 && start == -1 && s.charAt(i) == ' ') {
                start = i;
                break;
            }
        }
        return end - start;
    }
}
