/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class LinkedListCycle {
  public boolean hasCycle(ListNode head) {
    ListNode slow = head;
    ListNode fast = head;

    while (fast != null && fast.next != null) {

      slow = slow.next;
      fast = fast.next.next;

      if (fast == slow)
        return true;

    }
    return false;
  }
}
