/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.List;

public class LinkedListCycle {
  public boolean hasCycle(ListNode head) {
    if (head == null || head.next == null) {
      return false;
    }
    List<ListNode> checked = new ArrayList<>();
    checked.add(head);
    while (true) {
      if (head.next == null) {
        return false;
      }
      for (ListNode chd : checked) {
        if (chd == head.next) {
          return true;
        }
      }
      checked.add(head.next);
      head = head.next;
    }
  }
}
