/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.HashMap;
import java.util.Map;

public class MajorityElement {
  public int majorityElement(int[] nums) {
    if (nums.length == 1) {
      return nums[0];
    }
    int target = nums.length / 2 + 1;
    Map<Integer, Integer> map = new HashMap<>();
    for (int num : nums) {
      if (map.containsKey(num)) {
        int nextCount = map.get(num) + 1;
        if (nextCount == target) {
          return num;
        }
        map.put(num, nextCount);
      } else {
        map.put(num, 1);
      }
    }
    return 0;
  }
}
