/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class MaxSubArray {
    public int maxSubArray(int[] nums) {
        int max = -10000;
        for (int i = 0; i < nums.length; i++) {
            max = Math.max(max, findMax(nums, i));
        }
        return max;
    }

    public int findMax(int[] nums, int begining) {
        int max = -10000;
        int current = 0;
        for (int i = begining; i < nums.length; i++) {
            current += nums[i];
            max = Math.max(max, current);
        }
        return max;
    }
}
