/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayDeque;
import java.util.Deque;

public class MergeTwoSortedLists {
    public ListNode mergeTwoLists(ListNode list1, ListNode list2) {
        Deque<Integer> deque = new ArrayDeque<>();
        while (list1 != null || list2 != null) {
            if (list2 == null) {
                deque.push(list1.val);
                list1 = list1.next;
                continue;
            }
            if (list1 == null) {
                deque.push(list2.val);
                list2 = list2.next;
                continue;
            }
            if (list1.val <= list2.val) {
                deque.push(list1.val);
                list1 = list1.next;
            } else {
                deque.push(list2.val);
                list2 = list2.next;
            }
        }
        ListNode node = null;
        while (!deque.isEmpty()) {
            node = new ListNode(deque.poll(), node);
        }
        return node;
    }
}
