/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class NumberOf1Bits {
  // you need to treat n as an unsigned value
  public int hammingWeight(int n) {
    int counter = 0;
    int mask = 1;
    for (int i = 0; i < 32; i++) {
      if ((n & mask) != 0) {
        counter++;
      }
      mask <<= 1;
    }
    return counter;
  }
}
