/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Queue;

public class PalindromeLinkedList {
  public boolean isPalindrome(ListNode head) {
    Deque<Integer> deque = new ArrayDeque<>();
    Queue<Integer> queue = new ArrayDeque<>();
    while (head != null) {
      deque.push(head.val);
      queue.add(head.val);
      head = head.next;
    }
    while (!deque.isEmpty()) {
      if (deque.pop() != queue.poll()) {
        return false;
      }
    }
    return true;
  }
}
