/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PascalsTriangle2 {
  public List<Integer> getRow(int rowIndex) {
    List<Integer> prevRow = new ArrayList<>(Arrays.asList(1));
    for (int i = 0; i < rowIndex; i++) {
      List<Integer> row = new ArrayList<>();
      row.add(1);
      for (int j = 1; j < prevRow.size(); j++) {
        row.add(prevRow.get(j - 1) + prevRow.get(j));
      }
      row.add(1);
      prevRow = row;
    }
    return prevRow;
  }
}
