/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PascalsTriangle {
  public List<List<Integer>> generate(int numRows) {
    List<List<Integer>> result = new ArrayList<>();
    for (int i = 0; i < numRows; i++) {
      if (i == 0) {
        result.add(new ArrayList<>(Arrays.asList(1)));
      } else {
        result.add(getRowByPrevRow(result.get(result.size() - 1)));
      }
    }
    return result;
  }

  private List<Integer> getRowByPrevRow(List<Integer> prevRow) {
    List<Integer> result = new ArrayList<>();
    for (int i = 0; i < prevRow.size() + 1; i++) {
      if (i == 0 || i == prevRow.size()) {
        result.add(1);
      } else {
        result.add(prevRow.get(i - 1) + prevRow.get(i));
      }
    }
    return result;
  }
}
