/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class PathSum {
  public boolean hasPathSum(TreeNode root, int targetSum) {
    if (root == null) {
      return false;
    }
    if (root.left == null && root.right == null && root.val == targetSum) {
      return true;
    }

    boolean result = false;
    if (root.left != null) {
      root.left.val += root.val;
      result = result || hasPathSum(root.left, targetSum);
    }
    if (root.right != null) {
      root.right.val += root.val;
      result = result || hasPathSum(root.right, targetSum);
    }
    return result;
  }
}
