/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class RemoveDuplicatesFromSortedArray {
    public int removeDuplicates(int[] nums) {
        int index = 0;
        for (int i = 1; i < nums.length; i++) {
            if (nums[index] == nums[i]) {
                continue;
            }
            index++;
            nums[index] = nums[i];
        }
        return index + 1;
    }
}
