/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class RemoveElement {
    public int removeElement(int[] nums, int val) {
        int index = 0;
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] == val) {
                continue;
            }
            nums[index] = nums[i];
            index++;
        }
        return index;
    }
}
