/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class RemoveLinkedListElements {
  public ListNode removeElements(ListNode head, int val) {
    while (head != null && head.val == val) {
      head = head.next;
    }
    if (head == null) {
      return null;
    }
    ListNode dummy = new ListNode(-1, head);
    ListNode current = dummy.next;
    while (true) {
      if (current.next == null) {
        break;
      }
      if (current.next.val == val) {
        current.next = current.next.next;
      } else {
        current = current.next;
      }
    }
    return dummy.next;
  }
}
