/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class RemoveDuplicatesFromSortedArray {
    public int removeDuplicates(int[] nums) {
        int counter = 1;
        int current = nums[0];
        for (int i = 1; i < nums.length; i++) {
            if (current == nums[i]) {
                continue;
            }
            counter++;
            current = nums[i];
            nums[counter - 1] = current;
        }
        return counter;
    }
}
