/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class ReverseBits {
  // you need treat n as an unsigned value
  public int reverseBits(int n) {
    int ans = 0;
    for (int i = 31, j = 0; i >= 0 && j < 32; i--, j++) {
      int rightSlided = n >> j;
      int leftSlided = rightSlided << i;
      int mask = 1 << i;
      int val = leftSlided & mask;
      ans += val;
    }
    return ans;
  }
}
