/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class SearchInsertPosition {
    public int searchInsert(int[] nums, int target) {
        if (target > nums[nums.length - 1]) {
            return nums.length;
        }
        if (target <= nums[0]) {
            return 0;
        }
        if (nums.length == 1) {
            return target > nums[0] ? 1 : 0;
        }

        int begining = 0;
        int ending = nums.length - 1;
        while (true) {
            if (ending - begining <= 1) {
                break;
            }
            int middleIndex = (begining + ending) / 2;
            if (nums[middleIndex] >= target) {
                ending = middleIndex;
            } else {
                begining = middleIndex;
            }
        }

        return target == nums[begining] ? begining : ending;
    }
}
