/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.HashSet;
import java.util.Set;

public class SingleNumber {
  public int singleNumber(int[] nums) {
    Set<Integer> appeared = new HashSet<>();
    for (int num : nums) {
      if (appeared.contains(num)) {
        appeared.remove(num);
      } else {
        appeared.add(num);
      }
    }
    return appeared.iterator().next();
  }
}
