/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class Sqrt {
    public int mySqrt(int x) {
        // binary searching
        // condition to end
        if (x == 1) {
            return 1;
        }
        long ceiling = x;
        long floor = 0;
        while (true) {
            if (ceiling - floor == 1) {
                return (int) floor;
            }
            long ave = (ceiling + floor) / 2;
            if (ave * ave == x) {
                return (int) ave;
            } else if (ave * ave < x) {
                floor = ave;
            } else {
                ceiling = ave;
            }
        }
    }
}
