/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayList;
import java.util.List;

public class SummaryRanges {
  public List<String> summaryRanges(int[] nums) {
    List<String> result = new ArrayList<>();
    for (int i = 0; i < nums.length; i++) {
      if (i == 0) {
        result.add(Integer.toString(nums[i]));
        continue;
      }
      if (nums[i] == nums[i - 1] + 1) {
        if (i != nums.length - 1) {
          continue;
        }
        String lastInList = result.get(result.size() - 1);
        result.remove(result.size() - 1);
        result.add(lastInList + "->" + Integer.toString(nums[i]));
      } else {
        String lastInList = result.get(result.size() - 1);
        String lastInArray = Integer.toString(nums[i - 1]);
        if (!lastInList.equals(lastInArray)) {
          result.remove(result.size() - 1);
          result.add(lastInList + "->" + lastInArray);
        }
        result.add(Integer.toString(nums[i]));
      }
    }
    return result;
  }
}
