/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.ArrayDeque;
import java.util.Deque;

public class ValidParentheses {
    public boolean isValid(String s) {
        Deque<Character> deque = new ArrayDeque<>();
        if (s.length() % 2 == 1) {
            return false;
        }
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '(' -> deque.push(')');
                case '{' -> deque.push('}');
                case '[' -> deque.push(']');
                default -> {
                    if (deque.isEmpty() || ch != deque.poll()) {
                        return false;
                    }
                }
            }
        }
        return deque.isEmpty();
    }
}
