/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class ValidPalindrome {
  public boolean isPalindrome(String s) {
    int forIndex = 0;
    int revIndex = s.length() - 1;

    while (forIndex < revIndex) {
      while (!isAlphaNumeric(s.charAt(forIndex))) {
        forIndex++;
        if (forIndex > revIndex) {
          return true;
        }
      }
      while (!isAlphaNumeric(s.charAt(revIndex))) {
        revIndex--;
        if (forIndex > revIndex) {
          return true;
        }
      }
      if (Character.toLowerCase(s.charAt(forIndex)) == Character.toLowerCase(s.charAt(revIndex))) {
        forIndex++;
        revIndex--;
        continue;
      } else {
        return false;
      }
    }
    return true;
  }

  private boolean isAlphaNumeric(char chr) {
    return (chr >= 'a' && chr <= 'z') || (chr >= 'A' && chr <= 'Z') || (chr >= '0' && chr <= '9');
  }
}
